### ISSUE TITLE
Unable to use IDE extension in VS Code or Atom by October 2020

### ISSUE THREAD

**Issue by daniel-CreanteLab** [Elringus/NaninovelVSCode#1]
Does this occur consistently?  Yes
Repro steps:

1. Install VS Code
2. Go to view -> Extensions and look for Naninovel extension, click on install.
3. The extensions install correctly.
4. Proceed to open a .nani document on VS Code.
5. Launching extension apears and begins to load.
6. It fails showing the next message: "An error occurred while installing .NET: Dotnet Core Acquisition Failed: .NET installation timed out."
7.Proceed to download and install .NET Framework 4.8 from the official website.
8. As expected, when running the installer, it says that .Net is already installed on this machine.

Extension for Atom IDE stop working all of a sudden. Follow steps to re-install naninovel extension and Atom itself but it did not work either. This was done before opting to use the VS Code extension.

Action: naniscript.activate
Error type: Error
Error Message: Failed to install .NET runtime v3.1.

Version: 1.0.3
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
client.js:69:19client.js:69:19
fulfilled client.js:5:58
```

</details>

**Comment by Elringus** [comment]
> 7.Proceed to download and install .NET Framework 4.8 from the official website.
> Error Message: Failed to install .NET runtime v3.1

You need .NET Core 3.1 not .NET 4.8. Atom extension is deprecated.

**Comment by daniel-CreanteLab** [comment]
Thank you very much, it worked perfectly.
